[2024-11-28T21:44:46.707+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T21:44:46.733+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brewery_ETL.transform_gold manual__2024-11-28T21:39:21.032170+00:00 [queued]>
[2024-11-28T21:44:46.747+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brewery_ETL.transform_gold manual__2024-11-28T21:39:21.032170+00:00 [queued]>
[2024-11-28T21:44:46.748+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-28T21:44:46.762+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_gold> on 2024-11-28 21:39:21.032170+00:00
[2024-11-28T21:44:46.767+0000] {standard_task_runner.py:72} INFO - Started process 1466 to run task
[2024-11-28T21:44:46.772+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'brewery_ETL', 'transform_gold', 'manual__2024-11-28T21:39:21.032170+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/openbrewery_dag.py', '--cfg-path', '/tmp/tmppbaqvmql']
[2024-11-28T21:44:46.775+0000] {standard_task_runner.py:105} INFO - Job 219: Subtask transform_gold
[2024-11-28T21:44:46.841+0000] {task_command.py:467} INFO - Running <TaskInstance: brewery_ETL.transform_gold manual__2024-11-28T21:39:21.032170+00:00 [running]> on host c26ab963d4d9
[2024-11-28T21:44:46.950+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='brewery_ETL' AIRFLOW_CTX_TASK_ID='transform_gold' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T21:39:21.032170+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T21:39:21.032170+00:00'
[2024-11-28T21:44:46.951+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T21:44:46.976+0000] {transform_gold.py:148} INFO - Iniciando a tarefa transform_gold
[2024-11-28T21:44:46.977+0000] {transform_gold.py:162} INFO - Data de execução: 2024-11-28
[2024-11-28T21:44:46.977+0000] {transform_gold.py:16} INFO - Iniciando criação da sessão Spark para transformação Gold
[2024-11-28T21:44:54.706+0000] {transform_gold.py:41} INFO - Sessão Spark criada com sucesso para transformação Gold
[2024-11-28T21:44:54.707+0000] {transform_gold.py:50} INFO - Lendo dados da camada Silver: s3a://breweris-etl-prod-sp/silver/date=2024-11-28/
[2024-11-28T21:44:59.311+0000] {transform_gold.py:95} ERROR - Erro ao ler dados da camada Silver: [COLUMN_ALREADY_EXISTS] The column `date` already exists. Consider to choose another name or rename the existing column.
[2024-11-28T21:44:59.315+0000] {transform_gold.py:178} ERROR - Erro na tarefa transform_gold: [COLUMN_ALREADY_EXISTS] The column `date` already exists. Consider to choose another name or rename the existing column.
[2024-11-28T21:44:59.530+0000] {transform_gold.py:183} INFO - Sessão Spark finalizada para a tarefa transform_gold
[2024-11-28T21:44:59.531+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/transform_gold.py", line 168, in transform_gold
    df_silver = read_silver_data(spark, s3_bucket, s3_silver_path, execution_date)
  File "/opt/airflow/scripts/transform_gold.py", line 71, in read_silver_data
    df_silver = spark.read.schema(schema) \
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/readwriter.py", line 531, in parquet
    return self._df(self._jreader.parquet(_to_seq(self._spark._sc, paths)))
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/errors/exceptions/captured.py", line 175, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [COLUMN_ALREADY_EXISTS] The column `date` already exists. Consider to choose another name or rename the existing column.
[2024-11-28T21:44:59.558+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=brewery_ETL, task_id=transform_gold, run_id=manual__2024-11-28T21:39:21.032170+00:00, execution_date=20241128T213921, start_date=20241128T214446, end_date=20241128T214459
[2024-11-28T21:44:59.588+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T21:44:59.588+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 219 for task transform_gold ([COLUMN_ALREADY_EXISTS] The column `date` already exists. Consider to choose another name or rename the existing column.; 1466)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/transform_gold.py", line 168, in transform_gold
    df_silver = read_silver_data(spark, s3_bucket, s3_silver_path, execution_date)
  File "/opt/airflow/scripts/transform_gold.py", line 71, in read_silver_data
    df_silver = spark.read.schema(schema) \
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/readwriter.py", line 531, in parquet
    return self._df(self._jreader.parquet(_to_seq(self._spark._sc, paths)))
  File "/home/airflow/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/errors/exceptions/captured.py", line 175, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [COLUMN_ALREADY_EXISTS] The column `date` already exists. Consider to choose another name or rename the existing column.
[2024-11-28T21:44:59.634+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-28T21:44:59.669+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-28T21:44:59.671+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
