[2024-11-28T02:47:03.289+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T02:47:03.301+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T02:41:41.585930+00:00 [queued]>
[2024-11-28T02:47:03.307+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T02:41:41.585930+00:00 [queued]>
[2024-11-28T02:47:03.307+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-28T02:47:03.317+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_bronze> on 2024-11-28 02:41:41.585930+00:00
[2024-11-28T02:47:03.321+0000] {standard_task_runner.py:72} INFO - Started process 406 to run task
[2024-11-28T02:47:03.324+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'brewery_bronze_layer', 'load_bronze', 'manual__2024-11-28T02:41:41.585930+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/openbrewery_dag.py', '--cfg-path', '/tmp/tmpr0w1mr6w']
[2024-11-28T02:47:03.326+0000] {standard_task_runner.py:105} INFO - Job 64: Subtask load_bronze
[2024-11-28T02:47:03.367+0000] {task_command.py:467} INFO - Running <TaskInstance: brewery_bronze_layer.load_bronze manual__2024-11-28T02:41:41.585930+00:00 [running]> on host 422e0c9ce1aa
[2024-11-28T02:47:03.430+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='brewery_bronze_layer' AIRFLOW_CTX_TASK_ID='load_bronze' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T02:41:41.585930+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T02:41:41.585930+00:00'
[2024-11-28T02:47:03.431+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T02:47:03.444+0000] {load_bronze_module.py:88} INFO - Iniciando a tarefa load_bronze
[2024-11-28T02:47:03.567+0000] {load_bronze_module.py:98} INFO - Recebidos 8355 registros para carregar na camada Bronze
[2024-11-28T02:47:06.181+0000] {load_bronze_module.py:59} INFO - Sessão Spark criada com sucesso
[2024-11-28T02:47:06.181+0000] {load_bronze_module.py:102} INFO - Sessão Spark criada com sucesso
[2024-11-28T02:47:06.182+0000] {load_bronze_module.py:122} INFO - Criando DataFrame com Spark
[2024-11-28T02:47:06.409+0000] {load_bronze_module.py:144} ERROR - Erro ao salvar dados na camada Bronze: field longitude: FloatType() can not accept object '-97.46818222' in type <class 'str'>
[2024-11-28T02:47:06.587+0000] {load_bronze_module.py:148} INFO - Sessão Spark finalizada e tarefa load_bronze concluída
[2024-11-28T02:47:06.588+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/load_bronze_module.py", line 124, in load_bronze
    df_spark = spark.createDataFrame(data, schema=schema)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/session.py", line 1276, in createDataFrame
    return self._create_dataframe(
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/session.py", line 1318, in _create_dataframe
    rdd, struct = self._createFromLocal(map(prepare, data), schema)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/session.py", line 959, in _createFromLocal
    data = list(data)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/session.py", line 1292, in prepare
    verify_func(obj)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/types.py", line 2001, in verify
    verify_value(obj)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/types.py", line 1969, in verify_struct
    verifier(obj.get(f))
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/types.py", line 2001, in verify
    verify_value(obj)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/types.py", line 1995, in verify_default
    verify_acceptable_types(obj)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/types.py", line 1871, in verify_acceptable_types
    raise TypeError(
TypeError: field longitude: FloatType() can not accept object '-97.46818222' in type <class 'str'>
[2024-11-28T02:47:06.597+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=brewery_bronze_layer, task_id=load_bronze, run_id=manual__2024-11-28T02:41:41.585930+00:00, execution_date=20241128T024141, start_date=20241128T024703, end_date=20241128T024706
[2024-11-28T02:47:06.606+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T02:47:06.607+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 64 for task load_bronze (field longitude: FloatType() can not accept object '-97.46818222' in type <class 'str'>; 406)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/load_bronze_module.py", line 124, in load_bronze
    df_spark = spark.createDataFrame(data, schema=schema)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/session.py", line 1276, in createDataFrame
    return self._create_dataframe(
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/session.py", line 1318, in _create_dataframe
    rdd, struct = self._createFromLocal(map(prepare, data), schema)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/session.py", line 959, in _createFromLocal
    data = list(data)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/session.py", line 1292, in prepare
    verify_func(obj)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/types.py", line 2001, in verify
    verify_value(obj)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/types.py", line 1969, in verify_struct
    verifier(obj.get(f))
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/types.py", line 2001, in verify
    verify_value(obj)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/types.py", line 1995, in verify_default
    verify_acceptable_types(obj)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyspark/sql/types.py", line 1871, in verify_acceptable_types
    raise TypeError(
TypeError: field longitude: FloatType() can not accept object '-97.46818222' in type <class 'str'>
[2024-11-28T02:47:06.630+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-28T02:47:06.643+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-28T02:47:06.645+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
